### ISSUE TITLE
Cookbook ideas for walkdir crate

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rust-cookbook#112]
Come up with ideas for nice introductory examples of using [`walkdir`](https://docs.rs/walkdir), possibly in combination with other crates, that would be good to show in the Rust Cookbook. Please leave a comment here with your ideas! You don't necessarily have to write the example code yourself but PRs are always welcome!

- [x] [Recursively find all files with given predicate](https://github.com/brson/rust-cookbook/issues/125)
- [x] [Recursively find duplicate file names](https://github.com/brson/rust-cookbook/issues/126)
- [x] [Recursively calculate file sizes at given depth](https://github.com/brson/rust-cookbook/issues/179)
- [x] [Traverse directories while skipping dotfiles](https://github.com/brson/rust-cookbook/issues/202)

**Comment by budziq** [comment]
- [ ] recursively find all files with given predicate (date / extension / size / executable flag)
- [ ] find file duplicates in directory recursively

**Comment by dtolnay** [comment]
Thanks! I agree both of those would make great examples.

**Comment by Michael-F-Bryan** [comment]
What about recursively walking the directory structure and printing it to the screen somewhat like the `tree` command does?

```
$ tree src
src
├── document.rs
 ...
├── section.rs
└── visitor
    ├── mod.rs
    └── printer.rs
```

**Comment by budziq** [comment]
- recursively calculate file and directory sizes like in `du` command

**Comment by brson** [comment]
Maybe just "recursively calculate size of all files in a directory".

- Walk over a directory while skipping dotfiles. Common example featured in the walkdir docs.

**Comment by Henning-K** [comment]
How about (recursively) counting up all file types/endings from current directory on and printing them to the screen?

**Comment by clarcharr** [comment]
Searching for all Rust files in a directory, maybe? I do that with the [collapse-crate](https://github.com/clarcharr/collapse-crate) crate.

**Comment by cetra3** [comment]
Word count of a directory!

**Comment by vandenoever** [comment]
Compare two directories by using sorted iterators.

```rust
    let a = WalkDir::new("dir_a").sort_by(|a,b| a.cmp(b));
    let b = WalkDir::new("dir_b").sort_by(|a,b| a.cmp(b));
    for entry in a {
        ....
    }
```

**Comment by KodrAus** [comment]
From the [internals thread](https://internals.rust-lang.org/t/crate-evaluation-for-2017-06-13-walkdir/5306/5)

@imbaczek has suggested restructuring a directory based on mtime:

https://github.com/imbaczek/organize-by-mtime

**Comment by brson** [comment]
Thanks for all the ideas. Let's settle on some and keep moving.

> How about (recursively) counting up all file types/endings from current directory on and printing them to the screen?

@Henning-K There's a "recursively find files with given predicate" example [here](https://brson.github.io/rust-cookbook/app.html#recursively-find-all-files-with-given-predicate). Seems about what you are after.

> Searching for all Rust files in a directory, maybe?

@clarcharr Also seems functionally similar to previous example.

@vandenoever Comparing two directories seems plausible.

I wonder how many recipes we need for walkdir. I think we don't need too many. Most important to show off capabilities of the library for real tasks. The two we have ([1] [2]) actually don't seem to show distinct capabilities of walkdir between them.

The "compare two directories" idea at least shows `sort_by'.

Walkdir's [own docs](https://docs.rs/walkdir/1.0.7/walkdir/) basically show off `filter_entry` and `follow_links`, and amusingly neither of ours does. Can either of our existing be modified to use filter_entry instead?

I wonder what the advantage of `filter_entry` is over `into_iter().filter_map()`. Hm, I'm a bit confused.

[1]: https://brson.github.io/rust-cookbook/app.html#recursively-find-duplicate-file-names
[2]: https://brson.github.io/rust-cookbook/app.html#recursively-find-all-files-with-given-predicate

Other walkdir features that seem prominent that we're not showing off are min_dir / max_dir.

**Comment by brson** [comment]
I added "Recursively calculate file sizes at given depth" to the op based on @budziq since it leverages min_depth / max_depth.

**Comment by vandenoever** [comment]
if you want to highlight efficiency of walkdir vs find you could compare `find |sort` vs walkdir.sort_by. The latter is much more efficient in terms of memory and cpu.

**Comment by brson** [comment]
@burntsushi is not sure what the benefit of `filter_entry` over `filter_map` is.

**Comment by budziq** [comment]
@brson 

> what the benefit of filter_entry over filter_map is.

`filter_entry` does not descend into nodes failing the predicate while 

> Can either of our existing be modified to use filter_entry instead?

I guess that we could add `filter_entry`/ `follow_links` / `sort_by` to the already existing examples with some tweaking.

**Comment by KodrAus** [comment]
> I wonder what the advantage of filter_entry is over into_iter().filter_map(). Hm, I'm a bit confused.

@brson It looks like there are a few ergonomic differences. `filter_entry` takes a predicate like:

```rust
FnMut(&DirEntry) -> bool
```

Whereas `filter_map` would take a predicate like:

```rust
FnMut(Result<DirEntry>) -> Option<B>
```

If the `DirEntry` is a directory and the predicate doesn't match then it doesn't walk that directory, whereas `filter`/`filter_map` still will (I think).

**Comment by brson** [comment]
`filter_entry` will actually skip subdirectories when it can - if you return false on a directory, the entire subtree is skipped. So it seems like it's a best practice to use it, and we should probably prefer it for the recipes.

**Comment by KodrAus** [comment]
> So it seems like it's a best practice to use it, and we should probably prefer it for the recipes.

@brson I agree, let's always prefer `filter_entry` over the standard iterator filters in the cookbook examples and move the discussion over the [internals thread](https://internals.rust-lang.org/t/crate-evaluation-for-2017-06-13-walkdir/5306) if we want to explore `walkdir`s `filter_entry` vs `Iterator`'s `filter`/`filter_map` a bit more.

**Comment by budziq** [comment]
@KodrAus 
> let's always prefer filter_entry over the standard iterator filters 

Please note that `filter_entry` changes the semantics over `filter` which might be surprising and unwanted by the user (we might want to filter over files but descend to all dirs or filter dirs with separate predicate). These two would coexist. But I kinda find the `filter_entry` name braking the rule of least surprise.

**Comment by KodrAus** [comment]
@brson Should I raise another issue in this repo for using `filter_entry` in our `walkdir` samples?

**Comment by brson** [comment]
@budziq These semantic points would be good to point out in recipe text, and would be good to have some pretext in the cookbook for one example needing the short-circuiting behavior, and another needing to avoid the short-cirtuiting behavior. Can we think of how to rephrase one of the existing examples to want the short-circuiting, and the other to not, or otherwise come up with a new idea that fulfills these two criteria?

@KodrAus yes please. But do capture @budziq's point about the semantic differences not being clear cut.

**Comment by brson** [comment]
> I guess that we could add filter_entry/ follow_links / sort_by to the already existing examples with some tweaking.

@budziq hm, I feel like "Recursively find all files with given predicate" is pretty great as stated - it is a real simple common task. Let's not over complicate that one.

`filter_entry` would work well for a "Traverse directories while skipping dotfiles" example, which also skips hidden directories. I feel pretty good about this as a recipe. Common task. The text can explain the short-circuiting behavior on dot-directories. What do you think?

Per @burntsushi's [comment about `follow_symlinks`](https://internals.rust-lang.org/t/crate-evaluation-for-2017-06-13-walkdir/5306/9) it does seem like a good one to get in an example, with some text color about how it normalizes behavior across platforms.

I like the idea of tweaking "Recursively find duplicate file names" to follow symlinks - seems like a decent way to extend that example to show some unique functionality. Though "Recursively find duplicate file names while following symlinks" doesn't strike me as the perfect recipe - what does duplicate file names have to do with symlinks. Still, I think it is ok.

**Comment by BurntSushi** [comment]
> Though "Recursively find duplicate file names while following symlinks" doesn't strike me as the perfect recipe - what does duplicate file names have to do with symlinks

Well, it's not really about deduplication. You have two choices when recursively traversing a directory while following symlinks, where symlinks are used to create a loop:

1. Loop forever.
2. Detect loops, return an error, and refuse to continue descending ad infinitum.

This actually happens. Example on my system:

```
$ find -L /proc
...
find: File system loop detected; ‘/proc/self/task/18490/root/dev/fd/3/clones/fts-rs/test/cyclic/cyclic’ is part of the same file system loop as ‘/proc/self/task/18490/root/dev/fd/3/clones/fts-rs/test/cyclic’.
...
```

**Comment by budziq** [comment]
> "Recursively find duplicate file names while following symlinks" doesn't strike me as the perfect recipe 

Well the "while following symlinks" part does indeed sound artificial at best. I would suggest to keep the example title as it was "Recursively find duplicate file names" and just add implementation and textual description regarding symlinks

**Comment by BurntSushi** [comment]
I would object to calling anything that walkdir does "recursively find duplicate file names." That's not what it's doing. It's specifically detecting loops in the file system when it's asked to traverse symbolic links. For example, if two distinct symbolic links point to the same file, then walkdir will happily emit both of them.
