### ISSUE TITLE
Show off missing functionality in walkdir  examples

### ISSUE THREAD

**Issue by KodrAus** [rust-lang-nursery/rust-cookbook#182]
As raised in #112 our cookbook samples for `walkdir` should demonstrate the [`filter_entry`](https://docs.rs/walkdir/1.0.7/walkdir/trait.WalkDirIterator.html#method.filter_entry) method and note how it doesn't traverse directories if they don't match, unlike the standard `filter` method.

Original cookbook sample issues:

- #125
- #126

cc: @brson @budziq

---
edit. Action items below:
- [x] implement [Traverse directories while skipping dotfiles](https://github.com/brson/rust-cookbook/issues/202) using  [`filter_entry`](https://docs.rs/walkdir/*/walkdir/trait.WalkDirIterator.html#method.filter_entry) 
    - please describe the difference between  [`filter_entry`](https://docs.rs/walkdir/*/walkdir/trait.WalkDirIterator.html#method.filter_entry)  and [`Iterator::filter`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.filter) 
    - why we use it, what is the key difference
- [x] update [Recursively find all files with given predicate](https://brson.github.io/rust-cookbook/app.html#recursively-find-all-files-with-given-predicate)
 to use [`follow_links`](https://docs.rs/walkdir/*/walkdir/struct.WalkDir.html#method.follow_links)
- [x] ~~Propose and implement usage of [`sort_by`](https://docs.rs/walkdir/*/walkdir/struct.WalkDir.html#method.sort_by)~~

**Comment by budziq** [comment]
@KodrAus 

As discussed on https://github.com/brson/rust-cookbook/issues/112#issuecomment-305867666 I would also suggest to add
[`follow_symlinks`](https://docs.rs/walkdir/1.0.7/walkdir/struct.WalkDir.html#method.follow_links) to at least one of the examples

**Comment by tyoc213** [comment]
So well, what should I do?

**Comment by budziq** [comment]
Hi @tyoc213 I've added action items to this issue that you can follow. I would start with adding the [Traverse directories while skipping dotfiles](https://github.com/brson/rust-cookbook/issues/202)

**Comment by alisha17** [comment]
@tyoc213 Are you solving all the issues here? Or can I work on one of them? @budziq

**Comment by budziq** [comment]
These were left unattended long enough. I'm game either way :+1:

**Comment by alisha17** [comment]
@budziq To update [Recursively find duplicate filenames](https://brson.github.io/rust-cookbook/app.html#ex-dedup-filenames) to use follow_links, can you please elaborate on how symlinks can be used for this example?

**Comment by budziq** [comment]
it's a oneliner ;). Just add `.follow_links(true)` to the builder and update the prose to mention the added call.

On second thought the [Recursively find all files with given predicate](https://brson.github.io/rust-cookbook/app.html#recursively-find-all-files-with-given-predicate) will be better to showoff `follow_symlinks`. I'll update the todo list above

**Comment by tyoc213** [comment]
@alisha17 if you want to take one or two :)... 

@budziq if you have other suguestion(s)

**Comment by budziq** [comment]
@tyoc213 there is not much to do here really (unless  you can coma up with a nice usage of [`sort_by`](https://docs.rs/walkdir/*/walkdir/struct.WalkDir.html#method.sort_by) on one of the examples)

The only available (and actionable) example to implement left atm is https://github.com/brson/rust-cookbook/issues/207 so you can go for it if you feel like it (it will be super short too)
