### ISSUE TITLE
Cookbook ideas for error-chain crate

### ISSUE THREAD

**Issue by aturon** [rust-lang-nursery/rust-cookbook#184]
Come up with ideas for nice introductory examples of using `error-chain`, possibly in combination with other crates, that would be good to show in the Rust Cookbook. Please leave a comment here with your ideas! You don't necessarily have to write the example code yourself but PRs are always welcome!

edit
- [x] [Handle errors correctly in main](https://github.com/brson/rust-cookbook/issues/214)
- [x] [Avoid discarding errors during error conversions](https://github.com/brson/rust-cookbook/issues/215)
- [x] [Obtain backtrace of complex error scenarios](https://github.com/brson/rust-cookbook/issues/216)

**Comment by budziq** [comment]
@aturon This one might be a little tricky as over half of our examples already use `error-chain`.
It might be hard to come up with a "non-forced" example that shows something new without intimate knowledge.

Maybe some usage of [chaining-errors](https://docs.rs/error-chain/*/error_chain/#chaining-errors)?

cc @brson @Yamakaky

**Comment by Yamakaky** [comment]
Yeah, using it everywhere should be good. Maybe just add an error chain centered example ? Like "this thing would be easier with error chain, here is how to do it".

**Comment by brson** [comment]
I agree this one probably doesn't need a lot, but maybe it's possible to formulate recipe statements based off of common problems newbies have with errors.

e.g.

- "Handle errors correctly in `main`"
- "Avoid discarding errors during error conversions"

idk

**Comment by Yamakaky** [comment]
Yeah, sure.

**Comment by KodrAus** [comment]
For newbies even just _defining an error and using it_ seems like a useful example.

**Comment by Michael-F-Bryan** [comment]
I'd say something like defining an error type, then linking it to a couple other errors like `std::io::Error` or adding a couple custom variants is enough for a basic example. Then you can show an example of opening a file, using `?` and/or `chain_err()` to bubble up any errors encountered. That's about as much as I've needed to do for most of my crates. 

Another thing which may or may not be useful is printing a "backtrace" which looks something like this:

```rust
writeln!(stderr, "error: {}", e).unwrap();

for e in e.iter().skip(1) {
    writeln!(stderr, "\tcaused by: {}", e).unwrap();
}
```

(possibly swapping out `unwrap()` with `ok()`)

When making command line apps, I've sometimes done something like that when there was a fatal error and the `--verbose` flag is passed in.

**Comment by budziq** [comment]
@Michael-F-Bryan looks like your idea is on the spot. Although I would suggest splitting it to three separate examples of growing complexity based on the feedback so far:

- "Handle errors correctly in main" - super simple example which defines 1 error variant instead of using Box<Error>
- "Avoid discarding errors during error conversions" - slightly more complex example showing aggregation of custom and crate errors that might use `chain_err`
- "Obtain backtrace of complex error scenarios" - some realistic 3 level error handling (possibly based on largely stripped down version of [Download a file](https://brson.github.io/rust-cookbook/net.html#download-a-file-to-a-temporary-directory) example without tempdir/headder noise)

@brson @aturon  do these look ok to you?  If yes I'll create the specific issues and update the tracking issue.

**Comment by AndyGauge** [comment]
Closing tracking issue.  All requested recipes are complete.
