### ISSUE TITLE
Recipes for flate2 / tar

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rust-cookbook#185]
Ideas for the flate2 and tar crates (since they tend to be used together).

- [x] "Decompress a tarball to a directory"
- [x] ["Compress a directory to a tarball"](https://github.com/brson/rust-cookbook/issues/186)
- [x] ["Decompress a tarball while removing a prefix from the paths"](https://github.com/brson/rust-cookbook/issues/187)
  - Purpose of this is to iterate over the entries, not just use Archive::unpack

Looks like the decompress case is [already covered](https://brson.github.io/rust-cookbook/app.html#unzip-a-tarball-to-a-temporary-directory), while also showing off tempdir at the same time.

**Comment by brson** [comment]
It might be worthwhile to convert the existing tar / flate2 / tempdir example to just a tar / flate2 example, so it has some symmetry with the pending "compress a directory to a tarball" example, and come up with additional tempdir ideas.

**Comment by budziq** [comment]
I've removed tempdir from  "Decompress a tarball to a directory" in https://github.com/brson/rust-cookbook/issues/191
For what its worth we still have one [tempdir example](https://brson.github.io/rust-cookbook/net.html#ex-url-download) that might be a little "forced".
