### ISSUE TITLE
cookbook ideas for csv crate

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#212]
Come up with ideas for nice introductory examples of using [csv](https://crates.io/crates/csv) crate, possibly in combination with other crates, that would be good to show in the Rust Cookbook. Please leave a comment here with your ideas! You don't necessarily have to write the example code yourself but PRs are always welcome!

There are some excellent examples in [csv-cookbook](https://docs.rs/csv/1.0.0-beta.3/csv/cookbook/index.html) and [csv-tutorial](https://docs.rs/csv/1.0.0-beta.3/csv/tutorial/index.html) that we can adapt (coding style and description should be changed to rust-cookbook style)

- [x] [read csv records](https://github.com/brson/rust-cookbook/issues/228)
- [x] [read csv records with different delimeter](https://github.com/brson/rust-cookbook/issues/229)
- [x] [filter csv records matching a predicate](https://github.com/brson/rust-cookbook/issues/230)
- [x] [handle invalid csv data with serde](https://github.com/brson/rust-cookbook/issues/231)
- [x] [Serialize records to csv](https://github.com/brson/rust-cookbook/issues/232)
- [x] [Transform csv columns](https://github.com/rust-lang-nursery/rust-cookbook/issues/346)

**Comment by budziq** [comment]
initial ideas:
- "read csv records" - should show both reading into a `StringRecord` and typed deserialization with Serde (preferably in two separate short snippets)
- "read csv records with different delimeter"
- "filter csv records matching a predicate"
- "handle invalid csv data with serde" 
- "Serialize records to csv"

**Comment by alisha17** [comment]
I did two examples for this. Should I create a new page for csv in cookbook or put the examples under general 'Application Development'?

**Comment by budziq** [comment]
@alisha17 These will go to "encoding" section of the book.

but please post the ideas first as we are still soliciting the ideas and none have been accepted yet :)

**Comment by alisha17** [comment]
@budziq I worked on the initial ideas you mentioned in the comment above.

**Comment by budziq** [comment]
@alisha17 
> I worked on the initial ideas you mentioned in the comment above.

Which ones then? I'll create the issues

**Comment by alisha17** [comment]
-"read csv records with different delimeter"
-"handle invalid csv data with serde"
-"Serialize records to csv"
@budziq

**Comment by iamdanfox** [comment]
What about reading a CSV file and then transforming one column somehow? For example maybe the input data could be “url,time,browser” and then you could split up url into scheme, host, port, path. This might raise interesting error handling cases where a URL fails to parse

**Comment by budziq** [comment]
@iamdanfox cool idea! I've added issue based on your idea https://github.com/rust-lang-nursery/rust-cookbook/issues/346 Would you be interested in submitting a PR?
