### ISSUE TITLE
cookbook ideas for ring crate

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#213]
Come up with ideas for nice introductory examples of using [ring](https://crates.io/crates/ring) crate, possibly in combination with other crates, that would be good to show in the Rust Cookbook. Please leave a comment here with your ideas! You don't necessarily have to write the example code yourself but PRs are always welcome!

Come up with a compelling use case, possibly inspired by real usage on crates.io! [reverse dependencies](https://crates.io/crates/ring/reverse_dependencies) 

- [x] [Calculate the SHA-256 digest of a file](https://github.com/rust-lang-nursery/rust-cookbook/pull/257)
- [x] [Hash a password with salt](https://github.com/rust-lang-nursery/rust-cookbook/issues/288)
- [x] [Sign and verify a message with HMAC digest](https://github.com/rust-lang-nursery/rust-cookbook/issues/289)

**Comment by budziq** [comment]
initial ideas:
- calculate sha1 / sha256 digest of given data or file
- sign and verify a value with HMAC digest
- other non contrived examples

**Comment by Phaiax** [comment]
I don't believe we should add any examples of ring into the cookbook except for password hashing.
There is simply to much that can go wrong when rolling out selfmade cryptography schemes (or with its key management). Many of the reverse examples are just rust implementations of (more or less) known cryptography schemes. There are examples in the ring crate that are helpful and discoverable enough, but examples in the cookbook will increase the probability of someone trying to roll out its own crypto scheme.

I would propose a cookbook example for TLS secured server/client communication with certificate pinning, including how to create certificates etc. 

Second use case that may become common is an automatic self updater like `rustup self update`, but I have not found anything like that on crates.io.

**Comment by budziq** [comment]
@Phaiax 

> There is simply to much that can go wrong when rolling out selfmade cryptography schemes 

I totally agree. The idea behind cookbook is to take the crates and see what common programming usecases can be implemented with them (bonus points for other crates being involved). Rolling your own crypto is certainly not a common task (please see my comment on [internals thread](https://internals.rust-lang.org/t/rust-libz-blitz/5184/109?u=budziq) exactly about that :smile: )

> I would propose a cookbook example for TLS secured server/client communication with certificate pinning, including how to create certificates etc.
>
> Second use case that may become common is an automatic self updater like rustup self update, but I have not found anything like that on crates.io.

These look mighy interesting. 
Do you think that you could pull these off within the constraints of cookbook?
- single source file per executable
- relatively short example size (expanded [fractal example](https://brson.github.io/rust-cookbook/concurrency.html#ex-threadpool-fractal) is probably the longest we are willing to go ATM)

**Comment by luser** [comment]
I submitted a PR to add an example of generating a SHA-256 digest of a file with ring: https://github.com/brson/rust-cookbook/pull/257

**Comment by AndyGauge** [comment]
Ring is a bit esoteric, and I think we should keep its footprint at a minimum.  Most cryptography is pretty specialized.  I like the recipes already included.
