### ISSUE TITLE
cookbook ideas for regex crate 

### ISSUE THREAD

**Issue by budziq** [rust-lang-nursery/rust-cookbook#217]
Come up with ideas for nice introductory examples of using [regex](https://crates.io/crates/regex) crate, possibly in combination with other crates, that would be good to show in the Rust Cookbook. Please leave a comment here with your ideas! You don't necessarily have to write the example code yourself but PRs are always welcome!

We already have [one example](https://brson.github.io/rust-cookbook/basics.html#run-an-external-command-and-process-stdout) using the regex crate but it's not regexp focused. We could use some additional ones showing both less and more advanced crate usage

- [x] [Run an external command and process stdout](https://github.com/brson/rust-cookbook/issues/108)
- [x] [Validate an e-mail address and extract login](https://github.com/brson/rust-cookbook/issues/240)
- [x] [Extract phone numbers from text](https://github.com/brson/rust-cookbook/issues/241)
- [x] [Extract a list of unique #Hashtags from a text](https://github.com/brson/rust-cookbook/issues/242)
- [x] [Replace text with named capture groups](https://github.com/brson/rust-cookbook/issues/243)
- [x] [Filter a log file by matching multiple regular expressions](https://github.com/brson/rust-cookbook/issues/244)
- [x] [Extract all unique links from MediaWiki markup](https://github.com/brson/rust-cookbook/issues/245)

**Comment by budziq** [comment]
Any ideas for non contrived example?
 
Some initial ideas:
- validate e-mail address
- replace text with named capture groups
- Matching multiple regular expressions with `RegexSet`

**Comment by Phaiax** [comment]
- Parsing `href=""` and `src=""` from a webpage and deduplicate
- Extracting a deduplicated list of #Hashtags from a text
- Extracting a certain html tag including its content without parsing the whole document as html.
- Capturing urls to special domains. (for something like the automatic 'issue has been mentioned' system here on github)
- Filter a log file (remove Info/Debug...)
- Extract potential phone numbers
- Remove all html tags (including surrounding spaces) and replace them with one space, but leave the text between the tags.

**Comment by budziq** [comment]
@Phaiax these look awesome! Although I would avoid using regex in case a more specialized crate is already available in cookbook (as is the case for url and html parsing but I'm still game to represent the ideas in the cookbook). Would you be willing to implement some of these?

**Comment by AndyGauge** [comment]
The cookbook does a great job of showing both simple and advanced regex examples.  I'm going to close this tracking issue.
