### ISSUE TITLE
Cookbook ideas for the rand crate

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rust-cookbook#227]
We already have 4 examples:

- [x] Generate random floating point numbers
- [x] Generate random numbers within a range  
- [x] Generate random numbers with normal distribution
- [x] Generate random values of a custom type
- [x] [Create random passwords from a set of allowed characters](https://github.com/rust-lang-nursery/rust-cookbook/issues/287)
- [ ] TODO: review 0.5 API, suggest new recipes

So it's not obvious we need more. But here's an opportunity to reevaluate the set we've got and brainstorm about it.

**Comment by Phaiax** [comment]
Similar to the range example: Create random passwords from a set of allowed characters.

**Comment by mykalu** [comment]
How about an example of creating a specified-length vector of random numbers out of `rng.gen_iter()`?

**Comment by AndyGauge** [comment]
`Rand` is going through an overhaul.  0.5-pre 1 just came out.  I would like to revisit this issue once 0.5 ships and evaluate adding recipes later.

**Comment by AndyGauge** [comment]
I read the 0.5 Changelog and the stuff they added was great, but not really helpful to a wide audience.  Most of the changes were to support true randomness required for a security perspective.  I'm not sure there's a lot of value to a wide audience for this.  @pitdicker did a good job in #391 to update the API.  I think the cookbook has a good sample of Rand usage.
