### ISSUE TITLE
Miscellaneous cookbook ideas

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rust-cookbook#24]
The [Perl cookbook](http://shop.oreilly.com/product/9780596003135.do) or [Python cookbook](http://shop.oreilly.com/product/0636920027072.do) could be a good source of inspiration.

- [x] [Declare lazily evaluated constant](https://github.com/brson/rust-cookbook/issues/99) (lazy_static)
- [x] [Maintain global mutable state](https://github.com/brson/rust-cookbook/issues/100) (lazy_static)
- [x] [Unzip a tarball to a temporary directory](https://github.com/brson/rust-cookbook/issues/101) (temdir + tar + flate2)
- [x] [Dispatch work to a thread pool](https://github.com/brson/rust-cookbook/issues/102) (threadpool)
- [x] [Fork a short-lived thread that cheaply references data from the original thread](https://github.com/brson/rust-cookbook/issues/103) (crossbeam)
- [x] [Access a file randomly using a memory map](https://github.com/brson/rust-cookbook/issues/105) (memmap)
- [ ] TODO evaluate this issue and generate more recipes

**Comment by brson** [comment]
If you decide to implement one of the ideas in the op please say so here to claim it, so others don't duplicate the effort.

**Comment by alisha17** [comment]
I am going ahead with "Mutate elements of an array in parallel".

**Comment by karan1276** [comment]
I would like to work on "Dispatch work to a thread pool". I think problem statement "Sort an array of M numbers using N threads" will be optimal for demonstration. In case you had some other problem statement in mind let me know.

**Comment by brson** [comment]
Awesome. Thanks @alisha17 and @karan1276!

@karan1276 Your problem statement sounds good. I'm interested in seeing your solution.

**Comment by budziq** [comment]
First of all sorry if I am spamming the thread.

Looking from the perspective of busy programmer with little to no experience in rust (like myself) I would greatly appreciate a systematic and comprehensive approach like in the (already mentioned) [perl](http://shop.oreilly.com/product/9780596003135.do) or [python](http://shop.oreilly.com/product/0636920027072.do) cookbooks.

Please note that large part of the audience will be coming with basic problems (even if already discussed in other sources like [Rust by Example](http://rustbyexample.com/) ) like:
- basic iterator manipulation (for each / skipping / reversing / collecting / mapping / filtering / zippping / enumerating/sorting)
- implementing custom iterator
- more advanced iterator idioms - flattening nested sequences / cycling / grouping (possibly even with itertools)
- String splitting/concatenation/ struct representation (Display et al.)
- Finding substring occurences / replacing
- stripping unwanted characters from string
- regular expressions
- Dictionary lookup, finding set union / intersection / difference / complement,
- extracting subset
- listing items by frequency
- Basic threading (starting / joining / workqueue / locking / message passing) - there is plethora of usecases for which rayon is not the ideal answer
- recursively listing directories (walkdir)
- date time parsing / manipulation / calculation
- path manipulation
- statting files (testing for existance / size / atime / mtime etc.) / checking dent is a file / dir / link
- decoding/encoding - hex / base64
- implementing callbacks / working with closures
- creating UDP/TCP server
- manipulating files and directories (create / copy / move / delete)

Some intermediate usecases might be:
- connecting to database / performing sql querries
- orm (diesel)
- reading / writing - csv / json / yaml / toml / xml / ini
- processing large xml documents incrementally
- implementing some standard design patterns - visitor / strategy / state machine / builder / factory / command / ...
- creating cyclic data structures
- creating simple rest service
- xml-rpc / json-rpc client / server
- launching unix daemon
- logging
- testing / mocking / expecting failure / catching panics
- various FFI usecases - calling c from rust / calling rust from c / python / ruby

Some other problems that I have personally encountered:
- parsing binary file (I used nom but no parser combinator lib is listed in [key crate list](https://gist.github.com/brson/ff89e9709104bbdbde1c13cbf0db15ef))
- spawning process and communicating
- checking if executable exists in the system
- comparing large files (memmap)

@brson Do these examples look reasonable? In order to learn rust I would be willing to implement at least few of the listed examples.

**Comment by brson** [comment]
@budziq wow thank you for all these ideas. I think almost all of them are appropriate for the cookbook.

I would though like to keep the scope of the cookbook relatively aligned with the [libz blitz](https://internals.rust-lang.org/t/rust-libz-blitz/5184/19), where we are working sort of from the inside out, documenting the most fundamental crates first.

If you want to implement any of these examples I encourage you to pick ones that can be implemented with the crates discussed in that thread.

Some areas on your list I don't feel prepared to deal with yet are databases, testing and mocking, PRC.

I'm not sure that patterns are appropriate for this project, but there is at least one project dedicated to Rust patterns specifically.

Thanks so much for jumping on this @budziq. Keep it coming.

**Comment by kud1ing** [comment]
I've just discovered this and would add the few examples i have: https://github.com/kud1ing/rust-recipes

**Comment by derekdreery** [comment]
Run an external command and collect stdout

**Comment by j-haj** [comment]
Is there any interest in adding examples for the following crates:

* serde - data serialization/deserialization is a very useful and important tool. It would be a great combo with RPC, although there are no RPC crates in the libz blitz thread
* chrono - another userful crate. Adding a recipe for timing segments of code would be very useful to a lot of people I think (it's a very common question in Python, C, and C++, for example)

**Comment by budziq** [comment]
@j-haj these are both excellent points! 
- i agree on the serde front (it has some representation) . Although I was thinking in expanding the usage with some xml, yml and more toml examples. In regard to Rpc itself. It is a tough nut to crack. There seams to be no  community favourite crate for that purpose at the moment so we would have to do some digging and possibly a poll. Our [crate inclusion policy](https://github.com/rust-lang-nursery/rust-cookbook/issues/304) has just started coalescing.
- my thoughts exactly on chrono. I was just thinking about adding some date / time manipulation examples. Would you open the tracking issue for chrono to gather ideas?

**Comment by j-haj** [comment]
@budziq Done! see #324. It appears you may have to add the labels

**Comment by gbip** [comment]
What do you think about "Send a struct through a TCP connection" ?
In my opinion, using serde with a TcpStream and a TcpListener is something that could be really useful for any kind of server-client application.

**Comment by budziq** [comment]
@gbip Thanks!

>  using serde with a TcpStream and a TcpListener is something that could be really useful for any kind of server-client application.

While I think that an example showing basic connection handling and data sending/receiving with std would be beneficial, I'm not loving the idea of "sending struct" or using serde here. 

Here's why:
- Communication via passing structs is almost never a good idea, one would have to implement some rudimentary protocol.
- Do we frame, length prefix or delimit the messages/data?
- Which of the serde serializers would we use? [Bincode](https://github.com/TyOverby/bincode), [CBOR](https://github.com/pyfisch/cbor),
 [MessagePack](https://github.com/3Hren/msgpack-rust),[Pickle](https://github.com/birkenfeld/serde-pickle), [BSON](https://github.com/zonyitoo/bson-rs)
And which should we promote in the cookbook. Any of these are typically used in the context of some protocol and using these directly over TCP would be promoting non optimal patterns.

Personally I'd suggest to implement a basic TCP client server (like echo or datetime http://blog.annharter.com/2015/07/15/three-dead-protocols.html) pointing in the description that this is a basic toy example that should use Tokio/Mio for any kind of performance.
