### ISSUE TITLE
Cookbook ideas for std

### ISSUE THREAD

**Issue by richard-uk1** [rust-lang-nursery/rust-cookbook#266]
EDITED I'm not sure what the different options are regarding stdio, so here are some suggestions

--------
Current list:
- [x] [Run an external command and process stdout](https://rust-lang-nursery.github.io/rust-cookbook/basics.html#run-an-external-command-and-process-stdout)
- [x] [Run an external command passing it stdin and check for an error code](https://github.com/rust-lang-nursery/rust-cookbook/issues/268)
- [x] [Run piped external commands](https://github.com/rust-lang-nursery/rust-cookbook/issues/269)
- [x] [Measure elapsed time](https://github.com/rust-lang-nursery/rust-cookbook/issues/341)
- [x] [Redirect both stdout and stderr of child process to the same file](https://github.com/rust-lang-nursery/rust-cookbook/issues/345)
- [x] [Process child process output continuously](https://github.com/rust-lang-nursery/rust-cookbook/issues/339)
- [x] [Get files in directory modified in the last 24 hours](https://github.com/rust-lang-nursery/rust-cookbook/issues/399)
- [ ] [Implement FromStr](https://github.com/rust-lang-nursery/rust-cookbook/issues/400)
- [ ] [Read Environment variable to find Configuration file](https://github.com/rust-lang-nursery/rust-cookbook/issues/401)
- [ ] [Implement Display and Debug and Hash](https://github.com/rust-lang-nursery/rust-cookbook/issues/402)

**Comment by budziq** [comment]
@derekdreery thanks for the suggestions. 

We already have [Run an external command and process stdout](https://rust-lang-nursery.github.io/rust-cookbook/basics.html#run-an-external-command-and-process-stdout) example which is a little more advanced version of your 1'st suggestion. But I like the ideas 2-4.

How about combining the 2'nd and 3'rd suggestion into one and leaving the 4'th as is?
Would you be interested in submitting PR for any of these?

**Comment by derekdreery** [comment]
Yeah I can do that

**Comment by budziq** [comment]
@derekdreery excellent :+1: . I took the liberty of updating the description into a tracking issue if there will be any other example ideas. Would you like to work on both of these examples or on a specific one (I'll mark them as WIP to avoid duplicated work)?

**Comment by derekdreery** [comment]
Yeah I can do both, might be a few days, it's late here :P.

**Comment by mykalu** [comment]
[Run an external command and process stdout](https://rust-lang-nursery.github.io/rust-cookbook/basics.html#run-an-external-command-and-process-stdout) doesn't currently have `std` listed as one of its crates. Should it be added?

**Comment by budziq** [comment]
to one extent or the other all of the examples will use std. we are adding it more to denote lack of any other crate in use (otherwise this would be just noise)

**Comment by gbip** [comment]
What do you think about "Send a struct through a TCP connection" ?
In my opinion, using serde with a TcpStream and a TcpListener is something that could be really useful for any kind of server-client application.

**Comment by AndyGauge** [comment]
There are a ton of opportunities in std to add to the cookbook.  There's boxed, error, ffi, file systems, networking, strings, time, primitives.  We could write an entire chapter of `fmt`.

I'm going to try to think of some recipes that would showcase `std`.
