### ISSUE TITLE
Cookbook ideas for semver

### ISSUE THREAD

**Issue by KodrAus** [rust-lang-nursery/rust-cookbook#276]
Come up with ideas for nice introductory examples of using the [`semver`](https://github.com/steveklabnik/semver) crate, possibly in combination with other crates, that would be good to show in the Rust Cookbook. Please leave a comment here with your ideas! You don't necessarily have to write the example code yourself but PRs are always welcome!

- [x] [Parse and modify a version string](https://github.com/rust-lang-nursery/rust-cookbook/issues/283)
- [x] [Parse a complex version string](https://github.com/rust-lang-nursery/rust-cookbook/issues/284)
- [x] [Check if given version is pre-release](https://github.com/rust-lang-nursery/rust-cookbook/issues/316)
- [x] [Find the latest version satisfying given range](https://github.com/rust-lang-nursery/rust-cookbook/issues/285)
- [x] [Check external command version for compatibility](https://github.com/rust-lang-nursery/rust-cookbook/issues/286)

**Comment by budziq** [comment]
Possibly a good place to start is in the [crate reverse dependencies](https://crates.io/crates/semver/reverse_dependencies)

One application that comes right away is:
- check version of external command - i.e. parse output of "$my_binnary --version" external command

**Comment by KodrAus** [comment]
What about:

- parse and increment the major, minor or patch version based on input? (That's almost a 1-liner though)
- find the latest version in a set that satisfies the given range (like docs.rs does in its urls)

**Comment by mykalu** [comment]
Would these examples go into a new, "Semantic Versioning" section of the Cookbook, or the like?
("Crate Development", perhaps?)

**Comment by budziq** [comment]
@mykalu for now we will go with "Application development" and then split off some examples to new section when there  are enough of examples sharing some theme.

**Comment by mykalu** [comment]
`semver` is not currently filed under any category [on crates.io](https://crates.io/crates/semver). I'm looking at the [`Configuration`](https://crates.io/categories/config) category as a likely fit, but it's probably not my place to make a call on that. Any thoughts?

**Comment by budziq** [comment]
@mykalu Sound great to me! Any how it is easy enough to change and the crate will have a category added as the result of the Libz Blitz (would you like to propose your suggestion on their [evaluation thread](https://internals.rust-lang.org/t/out-of-band-crate-evaluation-for-2017-10-09-semver/5929)?).

**Comment by mykalu** [comment]
@budziq Sounds good, will do!

**Comment by anna-liao** [comment]
@KodrAus @budziq Just wondering, what is the etiquette if I am interested in working on a claimed issues that hasn't had an update in awhile?

**Comment by KodrAus** [comment]
@anna-liao Feel free to jump on any issues that have been idle for a while!

**Comment by budziq** [comment]
@anna-liao just ping me and the author mentioning that you would like to work on the issue from now on.

**Comment by AndyGauge** [comment]
All of the recommended recipes are merged.  There's no outstanding discussions here, I'm closing the tracking issue.
