### ISSUE TITLE
Tracking Issues

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#396]
We should triage the open tracking issues.  There are a lot of "complete" issues that linger.  
 - [x] [Miscellaneous cookbook ideas](https://github.com/rust-lang-nursery/rust-cookbook/issues/24)
 - [x] [Cookbook ideas for using a RESTful service](https://github.com/rust-lang-nursery/rust-cookbook/issues/43)
 - [x] [Cookbook ideas for reqwest crate](https://github.com/rust-lang-nursery/rust-cookbook/issues/84)
 - [x] [cookbook ideas for ring crate](https://github.com/rust-lang-nursery/rust-cookbook/issues/213)
 - [x] [cookbook ideas for regex crate](https://github.com/rust-lang-nursery/rust-cookbook/issues/217)
 - [x] [Cookbook ideas for the env_logger crate](https://github.com/rust-lang-nursery/rust-cookbook/issues/220)
 - [x] [Cookbook ideas for threadpool crate](https://github.com/rust-lang-nursery/rust-cookbook/issues/225)
 - [x] [Cookbook ideas for the rand crate](https://github.com/rust-lang-nursery/rust-cookbook/issues/227)
 - [x] [Cookbook ideas for std](https://github.com/rust-lang-nursery/rust-cookbook/issues/266)
 - [x] [Cookbook ideas for rayon](https://github.com/rust-lang-nursery/rust-cookbook/issues/272)
 - [x] [Cookbook ideas for semver](https://github.com/rust-lang-nursery/rust-cookbook/issues/276)
 - [x] [Cookbook ideas for num_cpus](https://github.com/rust-lang-nursery/rust-cookbook/issues/300)
 - [x] [Cookbook ideas for chrono](https://github.com/rust-lang-nursery/rust-cookbook/issues/324)

**Comment by AndyGauge** [comment]
It is my recommendation that we close everything except for Miscellaneous cookbook ideas.  I think we need to re-evaluate that one and pull some of the good ideas into new individual issues.

**Comment by AndyGauge** [comment]
Those that are checked off are ready.  (for those of you reading this in the future, there's nothing checked yet).  I will go through and close them or add to them.

**Comment by AndyGauge** [comment]
So I've closed 8 or so of them and added comments.  What we really need is more recipes at this time.
