### ISSUE TITLE
Cookbook 1.0

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang-nursery/rust-cookbook#414]
What will it take for us to call the cookbook 1.0?

First thing: A huge shout out to @budziq and the improvements he has made to the cookbook.  I am continually impressed by your effort.

I want to draw a line in the sand that we can release the cookbook.  What I think should be in scope of this release:

- [x] [mdbook v.0.1.7](https://github.com/rust-lang-nursery/rust-cookbook/pull/409)
- [x] [Reorganize](https://github.com/rust-lang-nursery/rust-cookbook/issues/375) #404 (ready)
- [x] [Spell Checker](https://github.com/rust-lang-nursery/rust-cookbook/issues/358) #410 (ready)
- [x] [proofread run](https://github.com/rust-lang-nursery/rust-cookbook/issues/139) #404 (ready)
- [x] [broken links](https://github.com/rust-lang-nursery/rust-cookbook/issues/408) #404 (ready)
- [x] [spell checker only](https://github.com/rust-lang-nursery/rust-cookbook/issues/358) #410 (ready)
- [x] [table sync issue](https://github.com/rust-lang-nursery/rust-cookbook/issues/280) #404 (ready)
- [x] [link checker](https://github.com/rust-lang-nursery/rust-cookbook/issues/356) #410 (ready)
- [x] [Update Contributing and PR Template for linters](https://github.com/rust-lang-nursery/rust-cookbook/issues/421) #404 (ready)
- [x] [use mdbook master branch?](https://github.com/rust-lang-nursery/rust-cookbook/issues/414#issuecomment-394837239)

What I want to keep active (for post 1.0) is:
- [ ] [Overhaul](https://github.com/rust-lang-nursery/rust-cookbook/issues/246)

There are a few PRs that are sitting in the queue.  It is going to take some effort to get them to merge after #404 lands.  I'd be happy to finish the outstanding work on them and include them in a 1.0 release.

Here's the original discussion at [ecosystem-wg](https://github.com/rust-lang-nursery/ecosystem-wg/issues/5).

I'd love some feedback on what you'd like to see done before stamping the Rust Cookbook 1.0

**Comment by budziq** [comment]
I fully agree with the idea!

Ive created a [milestone](https://github.com/rust-lang-nursery/rust-cookbook/milestone/2) to aggregate the issues that most likely should be addressed before 1.0 release.

I'd propose to also address:
- [ ] [proofread run](https://github.com/rust-lang-nursery/rust-cookbook/issues/139)
- [ ] [broken links](https://github.com/rust-lang-nursery/rust-cookbook/issues/408)
- [ ] [spell checker only](https://github.com/rust-lang-nursery/rust-cookbook/issues/358)

optionally:
- [ ] [table sync issue](https://github.com/rust-lang-nursery/rust-cookbook/issues/280)
- [ ] [link checker](https://github.com/rust-lang-nursery/rust-cookbook/issues/356)

Not sure if we will be ready for 1.0 then but it should be a good approximation to present to the libs team :)

**Comment by AndyGauge** [comment]
I think we are only missing the updates to the CONTRIBUTING and PR Template to support this purposed 1.0 rewrite.

**Comment by AndyGauge** [comment]
Actually, we need to determine if the Cookbook will rely on a git version of mdbook or wait until 1.8 drops.  Either way, build scripts and README needs to be updated.

**Comment by AndyGauge** [comment]
In order to build mdbook from master on rust 1.27, https://github.com/rust-lang/cargo/issues/5627 dictates specifying the version (--version 0.1.8-alpha.0) which is brittle.  I want to wait until 0.1.8 lands unless rust 1.28 stabilizes first.

**Comment by AndyGauge** [comment]
0.1.8 landed this morning, I built the branch successfully!

**Comment by AndyGauge** [comment]
I merged the Reorganize branch #404 
Watching for issues in the CI.

**Comment by budziq** [comment]
Thanks for pushing this through the finish line @AndyGauge ! :tada: :heart:

**Comment by AndyGauge** [comment]
Our imaginary line in the sand is complete.
