### ISSUE TITLE
Cookbook ideas for using a RESTful service

### ISSUE THREAD

**Issue by konstin** [rust-lang-nursery/rust-cookbook#43]
All major websites and many services provide restful apis. Using those has become a very important topic, be it for retrieving information from websites, interacting with common third-party service or communicating in an internal network. 

Ideally, a whole chapter should be dedicated to this topic. It should explaining the following subjects, which are ordered in descending priority:

- [x] Get from an endpoint url to the needed data; this should include the GET request, parsing json and extracting data (added in #80)
- [x] POST a JSON body (added in #80)
- [x] [POST the contents of a file](https://github.com/brson/rust-cookbook/issues/90)
- [x] [Set custom header and url parameters](https://github.com/brson/rust-cookbook/issues/91)
- [x] [Iterate through paginated requests](https://github.com/brson/rust-cookbook/issues/92)
- [x] [Tools for using advanced authentication techniques (e.g. oauth)](https://github.com/brson/rust-cookbook/issues/94); this does not need an explicit example but rather a link to the relevant crates
- [x] [Handling errors such as rate limits](https://github.com/brson/rust-cookbook/issues/93)

**Comment by brson** [comment]
Yes, this is a great idea, and it's not trivial.

Maybe some of these ideas can be split into multiple examples to avoid overwhelming.

What crate's would we need for the most basic example? reqwest, serde_json, url, others?

**Comment by konstin** [comment]
For my crate I use reqwest and json. I can't use serde due to the freedom in the api specification. Url is included as transitive dependency and re-exported through reqwest. It might be reasonable to provide examples with json and with serde as each has its usecases.

The bullet points should have a good size for a single example. The following is e.g. my code for GET, parsing and returning json. (I'm very open to improvements - it's the best I was able to write using the current docs)
```rust
fn get_json(&self, url: Url) -> Result<JsonValue, Box<Error>> {
    println!("Loading: {:?}", &url);
    let mut reponse = reqwest::get(url)?;
    if !reponse.status().is_success() {
        return Err(From::from(format!("Bad status code returned for request: {}",
                                      reponse.status())));
    }

    let mut json_string = String::new();
    reponse.read_to_string(&mut json_string)?;
    Ok(json::parse(&json_string)?)
}
```

Another idea that comes to my mind is including an example using chrono for proper timestamp formatting.

**Comment by dtolnay** [comment]
Would you be able to elaborate on this part?

> I can't use serde due to the freedom in the api specification.

This is what I would expect for analogous code using Serde:

```rust
extern crate serde_json;

use serde_json::Value;

fn get_json(&self, url: Url) -> Result<Value, Box<Error>> {
    println!("Loading: {:?}", &url);
    let response = reqwest::get(url)?;
    if !response.status().is_success() {
        return Err(From::from(format!("Bad status code returned for request: {}",
                                      response.status())));
    }
    Ok(serde_json::from_reader(response)?)
}
```

**Comment by konstin** [comment]
I though serde was for deserializing into structs. But with that new option I'm definitely going to try serde! So there's likely no need for json-rust at all

**Comment by brson** [comment]
@konstin a self-contained example about the size of the one in your previous post would be a fine addition.

**Comment by budziq** [comment]
Hi, I have implemented two relevant examples ("Query the GitHub API" idea taken from #24)

HTTP GET repo stargazers:
https://play.integer32.com/?gist=37adc825a9f373a3d2d38f0ab7a8672f&version=undefined

HTTP POST and DELETE: create a gist file and delete it
https://play.integer32.com/?gist=119d16cef32681c96a04058ba6c3514c&version=undefined

These still need cleanup and textual description etc.. Hopefully I will have some time tomorrow.

**Comment by dtolnay** [comment]
I edited a checklist into the OP and filed individual issues to follow up on the remaining ones.

**Comment by AndyGauge** [comment]
The cookbook is a bit heavy on HTTP patterns.  There is no additional comments here that haven't been completed.  I'm closing this issue.
