### ISSUE TITLE
Cookbook ideas for reqwest crate

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rust-cookbook#84]
Come up with ideas for nice introductory examples of using [`reqwest`](https://docs.rs/reqwest), possibly in combination with other crates, that would be good to show in the Rust Cookbook. Please leave a comment here with your ideas! You don't necessarily have to write the example code yourself but PRs are always welcome!

- [x] [Make an HTTP GET request](https://brson.github.io/rust-cookbook/net.html#ex-url-basic) (reqwest)
- [x] [Download a file to a temporary directory](https://brson.github.io/rust-cookbook/net.html#ex-url-download) (reqwest + tempdir)
- [x] [Make a partial download with HTTP range headers](https://github.com/rust-lang-nursery/rust-cookbook/issues/291) (reqwest)
- [x] [Query the GitHub API](https://brson.github.io/rust-cookbook/net.html#ex-rest-get) (reqwest + serde)
- [x] [Create and delete Gist with GitHub API](https://brson.github.io/rust-cookbook/net.html#ex-rest-post) (reqwest + serde)
- [x] [Use HEAD request to test whether endpoint exists](https://github.com/brson/rust-cookbook/issues/109) (reqwest)
- [x] [Extract all links from a webpage](https://github.com/brson/rust-cookbook/issues/110) (reqwest + select)
- [x] [Check webpage for broken links](https://github.com/rust-lang-nursery/rust-cookbook/issues/290) (reqwest + select)
- [ ] TODO evaluate the remaining comments on this page and decide if recipes are in scope.

[*Crate evaluation thread on internals.rust-lang.org*](https://internals.rust-lang.org/t/crate-evaluation-for-2017-05-30-reqwest/5248)

**Comment by budziq** [comment]
In addition to already created issues i would suggest:
- [ ] using HEAD request to test endpoint/file existence (or just check headders)
- [ ] use PUT / PATCH requests (GitHub has some apis like that) although it might be a little redundant
- [ ] test if links on webpage are stale - [html5ever](https://crates.io/crates/html5ever) or [select](https://crates.io/crates/select)

I guess that following might be out of scope and a little redundant:
Possibly just show some interesting web apis (twitter) but most of these would be to involved due to oAuth (or require very high level crate [oauth-client](https://crates.io/crates/oauth-client)  )
- [ ] Interact with twitter API - make a tweet
- [ ] google translate
- [ ] google geocoder / reverse geocoder
- [ ] stack overflow

**Comment by dtolnay** [comment]
I am open to showing a variety of common interesting web APIs. OAuth is a little more involved than I would like for the cookbook. I would prefer to handle it by linking from the basic-auth GitHub example to the oauth-client documentation: #94.

**Comment by budziq** [comment]
- Make a partial download with range headers

**Comment by Michael-F-Bryan** [comment]
This is a bit of a more advanced idea, but I recently wrote [a wrapper] around the github API for dealing with pagination by giving you an iterator which automatically requests the next page and deserializes it using serde. 

Would something like that be a useful cookbook recipe, or is it too much of a niche problem?

[a wrapper]: https://github.com/Michael-F-Bryan/github-backup/blob/fc9e3db72ae064d28c111c07ffc4d31904086e66/src/raw_github.rs#L24-L122

**Comment by budziq** [comment]
Hi @Michael-F-Bryan. Thanks for taking an interest!
We already have an [example showing paginated response](https://brson.github.io/rust-cookbook/net.html#consume-a-paginated-restful-api) and we are trying to avoid pulling non LibzBlitz crates at the moment but you are welcome to submit your crate for inclusion in the [official thread](https://internals.rust-lang.org/t/rust-libz-blitz/5184) or contribute in any way such as:

- to fix the existing example
- implement new examples
- propose new examples for any crate
- improve cookbook in any way (including ui/ux)

We'd love to have you on board!

**Comment by Michael-F-Bryan** [comment]
Ah, looks like you guys are one step ahead of me! I was thinking you might be able to copy the guts out of my `Pagination` struct and adapt it to use `reqwest` instead of the `github-rs` client (which itself is just a thin wrapper around hyper). But you probably wouldn't gain much by altering the existing example to take inspiration from what I did other than showing how it's almost trivial to make the `Pagination` wrapper generic over anything which is deserializable using serde.

**Comment by fawix** [comment]
I like the pagination idea.
may I also suggest the different authentication methods as cookbook examples for reqwest?

- [ ] Basic authentication
- [ ] Basic hidden authentication
- [ ] Digest authentication
- [ ] Digest authentication with algorithm

we can use httpbin for those, as in this one for digest:
`curl -vv --digest -k -u "user:pass"  "https://httpbin.org/digest-auth/auth/user/pass/MD5`

**Comment by AndyGauge** [comment]
Created remaining Reqwest recipes, closing tracking issue.
